# Generated by Django 3.0.8 on 2020-07-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_waterfalls_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterfall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
